// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilework.CertificateManagement.Persistence;

#nullable disable

namespace certificatemanagement.tile.Migrations
{
    [DbContext(typeof(CertificateManagementContext))]
    [Migration("20250816124246_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Tilework.CertificateManagement.Persistence.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateDataString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrivateKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PrivateKeyId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Tilework.CertificateManagement.Persistence.Models.CertificateAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CertificateAuthorities");
                });

            modelBuilder.Entity("Tilework.CertificateManagement.Persistence.Models.PrivateKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Algorithm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyDataString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrivateKeys");
                });

            modelBuilder.Entity("Tilework.CertificateManagement.Persistence.Models.Certificate", b =>
                {
                    b.HasOne("Tilework.CertificateManagement.Persistence.Models.CertificateAuthority", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.CertificateManagement.Persistence.Models.PrivateKey", "PrivateKey")
                        .WithMany()
                        .HasForeignKey("PrivateKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("PrivateKey");
                });
#pragma warning restore 612, 618
        }
    }
}
