// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilework.LoadBalancing.Persistence;

#nullable disable

namespace loadbalancing.tile.Migrations
{
    [DbContext(typeof(LoadBalancerContext))]
    [Migration("20241226165144_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Listener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LoadBalancerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoadBalancerId");

                    b.ToTable("Listeners");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LoadBalancers");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListenerId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuleId")
                        .IsUnique();

                    b.ToTable("TargetGroups");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Listener", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", "LoadBalancer")
                        .WithMany("Listeners")
                        .HasForeignKey("LoadBalancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadBalancer");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.Listener", "Listener")
                        .WithMany("Rules")
                        .HasForeignKey("ListenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listener");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "TargetGroup")
                        .WithMany("Targets")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.Rule", "Rule")
                        .WithOne("Group")
                        .HasForeignKey("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Listener", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", b =>
                {
                    b.Navigation("Listeners");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.Navigation("Group")
                        .IsRequired();
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
