// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilework.LoadBalancing.Persistence;

#nullable disable

namespace loadbalancing.tile.Migrations
{
    [DbContext(typeof(LoadBalancerContext))]
    [Migration("20250302095746_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.ApplicationListener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadBalancerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoadBalancerId");

                    b.ToTable("ApplicationListeners");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LoadBalancers");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.NetworkListener", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadBalancerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoadBalancerId");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("NetworkListeners");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListenerId");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TargetGroups");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.ApplicationListener", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", "LoadBalancer")
                        .WithMany("ApplicationListeners")
                        .HasForeignKey("LoadBalancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoadBalancer");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.NetworkListener", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", "LoadBalancer")
                        .WithMany("NetworkListeners")
                        .HasForeignKey("LoadBalancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "Group")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("LoadBalancer");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.ApplicationListener", "Listener")
                        .WithMany("Rules")
                        .HasForeignKey("ListenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "Group")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Listener");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "TargetGroup")
                        .WithMany("Targets")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.ApplicationListener", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.LoadBalancer", b =>
                {
                    b.Navigation("ApplicationListeners");

                    b.Navigation("NetworkListeners");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
