// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilework.LoadBalancing.Persistence;

#nullable disable

namespace loadbalancing.tile.Migrations
{
    [DbContext(typeof(LoadBalancerContext))]
    partial class LoadBalancerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BaseLoadBalancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LoadBalancers");

                    b.HasDiscriminator().HasValue("BaseLoadBalancer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListenerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ListenerId");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TargetGroups");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.ApplicationLoadBalancer", b =>
                {
                    b.HasBaseType("BaseLoadBalancer");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ApplicationLoadBalancer");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.NetworkLoadBalancer", b =>
                {
                    b.HasBaseType("BaseLoadBalancer");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("LoadBalancers", t =>
                        {
                            t.Property("Protocol")
                                .HasColumnName("NetworkLoadBalancer_Protocol");
                        });

                    b.HasDiscriminator().HasValue("NetworkLoadBalancer");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Rule", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.ApplicationLoadBalancer", "Listener")
                        .WithMany("Rules")
                        .HasForeignKey("ListenerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listener");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.Target", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "TargetGroup")
                        .WithMany("Targets")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.NetworkLoadBalancer", b =>
                {
                    b.HasOne("Tilework.LoadBalancing.Persistence.Models.TargetGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.TargetGroup", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Tilework.LoadBalancing.Persistence.Models.ApplicationLoadBalancer", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
