// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilework.Core.Persistence;

#nullable disable

namespace tilework.core.Migrations
{
    [DbContext(typeof(TileworkContext))]
    [Migration("20251127185719_TokenVault")]
    partial class TokenVault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("LoadBalancerCertificates", b =>
                {
                    b.Property<Guid>("BalancerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("TEXT");

                    b.HasKey("BalancerId", "CertificateId");

                    b.HasIndex("CertificateId");

                    b.ToTable("LoadBalancerCertificates");
                });

            modelBuilder.Entity("Tilework.Persistence.CertificateManagement.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateDataString")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fqdn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrivateKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PrivateKeyId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Tilework.Persistence.CertificateManagement.Models.CertificateAuthority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CertificateAuthorities");
                });

            modelBuilder.Entity("Tilework.Persistence.CertificateManagement.Models.PrivateKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Algorithm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyDataString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrivateKeys");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.BaseLoadBalancer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LoadBalancers");

                    b.HasDiscriminator().HasValue("BaseLoadBalancer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LoadBalancerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoadBalancerId");

                    b.HasIndex("TargetGroupId");

                    b.HasIndex("Priority", "LoadBalancerId")
                        .IsUnique();

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetGroupId", "Host", "Port")
                        .IsUnique();

                    b.ToTable("Targets");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.TargetGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TargetGroups");
                });

            modelBuilder.Entity("Tilework.Persistence.TokenVault.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.ApplicationLoadBalancer", b =>
                {
                    b.HasBaseType("Tilework.Persistence.LoadBalancing.Models.BaseLoadBalancer");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ApplicationLoadBalancer");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.NetworkLoadBalancer", b =>
                {
                    b.HasBaseType("Tilework.Persistence.LoadBalancing.Models.BaseLoadBalancer");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetGroupId")
                        .HasColumnType("TEXT");

                    b.HasIndex("TargetGroupId");

                    b.ToTable("LoadBalancers", t =>
                        {
                            t.Property("Protocol")
                                .HasColumnName("NetworkLoadBalancer_Protocol");
                        });

                    b.HasDiscriminator().HasValue("NetworkLoadBalancer");
                });

            modelBuilder.Entity("LoadBalancerCertificates", b =>
                {
                    b.HasOne("Tilework.Persistence.LoadBalancing.Models.BaseLoadBalancer", null)
                        .WithMany()
                        .HasForeignKey("BalancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.Persistence.CertificateManagement.Models.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tilework.Persistence.CertificateManagement.Models.Certificate", b =>
                {
                    b.HasOne("Tilework.Persistence.CertificateManagement.Models.CertificateAuthority", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tilework.Persistence.CertificateManagement.Models.PrivateKey", "PrivateKey")
                        .WithMany()
                        .HasForeignKey("PrivateKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("PrivateKey");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.Rule", b =>
                {
                    b.HasOne("Tilework.Persistence.LoadBalancing.Models.ApplicationLoadBalancer", "LoadBalancer")
                        .WithMany("Rules")
                        .HasForeignKey("LoadBalancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tilework.Persistence.LoadBalancing.Models.TargetGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Tilework.LoadBalancing.Models.Condition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("RuleId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.PrimitiveCollection<string>("Values")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RuleId", "__synthesizedOrdinal");

                            b1.ToTable("Rules");

                            b1.ToJson("Conditions");

                            b1.WithOwner()
                                .HasForeignKey("RuleId");
                        });

                    b.Navigation("Conditions");

                    b.Navigation("LoadBalancer");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.Target", b =>
                {
                    b.HasOne("Tilework.Persistence.LoadBalancing.Models.TargetGroup", "TargetGroup")
                        .WithMany("Targets")
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.NetworkLoadBalancer", b =>
                {
                    b.HasOne("Tilework.Persistence.LoadBalancing.Models.TargetGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.TargetGroup", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("Tilework.Persistence.LoadBalancing.Models.ApplicationLoadBalancer", b =>
                {
                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
